# Generated by Django 2.0.2 on 2018-03-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='currency',
            field=models.CharField(default='PHP', max_length=3),
        ),
    ]
